# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.1.0-dev-2aad385b5
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-10T17:51:45Z"
  labels:
    app: crazy-frog-pod
  name: crazy-frog-pod
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    image: localhost/nginx-test:latest
    name: crazy-frog
    ports:
    - containerPort: 80
      hostPort: 8080
